name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: rm -rf node_modules/
      - run: npm install --production
      - run: npm run build
        env:
          CI: ""
      - run: curl -s https://get.simplelocalize.io | bash
